# -*- coding: utf-8 -*-
"""AI Intern

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1neKrchiTY-SQ_Z2JDeh50J5FmrZAyCmB

Prompt (Instruct ChatGPT to parse resume)

You are to act as a resume parser. I will provide you with a text resume, and your task is to parse it and output the content in JSON format. The JSON should include the following fields:

- Name
- Contact Information
  - Email
  - Phone
  - Address
- Summary / Objective
- Work Experience
  - Job Title
  - Company
  - Start Date
  - End Date
  - Location
  - Description
- Education
  - Degree
  - Institution
  - Start Date
  - End Date
  - Location
- Skills
- Certifications
- Projects
- Languages
- Other Information

Here's the text resume:

<table>
<!-- Include your resume details here -->
</table>
"""

config.yaml

openai_api_key: "YOUR_OPENAI_API_KEY"

# resume_parser.py
import openai
import yaml

# Load the config file
with open("config.yaml", "r") as file:
    config = yaml.safe_load(file)

# Define OpenAI API key
openai.api_key = config["openai_api_key"]

def format_resume_to_json(resume_text):
    prompt = f"""
You are to act as a resume parser. I will provide you with a text resume, and your task is to parse it and output the content in JSON format. The JSON should include the following fields:

- Name
- Contact Information
  - Email
  - Phone
  - Address
- Summary / Objective
- Work Experience
  - Job Title
  - Company
  - Start Date
  - End Date
  - Location
  - Description
- Education
  - Degree
  - Institution
  - Start Date
  - End Date
  - Location
- Skills
- Certifications
- Projects
- Languages
- Other Information

Here's the text resume:

{resume_text}
"""

    response = openai.Completion.create(
        engine="davinci-codex",
        prompt=prompt,
        max_tokens=1500,
        n=1,
        stop=None,
        temperature=0.5,
    )

    return response.choices[0].text.strip()

if __name__ == "__main__":
    # Load Resume Text
    with open("resume.txt", "r") as resume_file:
        resume_content = resume_file.read()

    result_json = format_resume_to_json(resume_content)

    # Print or save the result
    print(result_json)
    with open("parsed_resume.json", "w") as json_file:
        json_file.write(result_json)

pip install openai pyyaml

python resume_parser.py



